* Fred Mitchell's GitHub
  I am a Software Architect / Engineer / Developer / Computer Scientist
  or whatever interests me at the moment.

** Aspirations
   I hope to be able to bring about AGI someday. I already have a good idea how
   to do this, based on the dedicated research of others. However, we will
   ultimately need a new kind of hardware to pull it off. Von Neumann-type machines 
   have an inherent bottleneck. And forget gradient descent approaches, or even running
   on GPUs. They simply cannot scale to what is needed.
   
   I, now, as on 2022, have an idea for such hardware, but I need to do a ton of research. As
   an old mentor once said: creativity is 1% inspiration and 99% perspiration. And my time
   is limited, and I am not getting any younger. 
   
   I am also trying to resolve how I can merge the concepts of NEAT and HTM to produce something truly novel.
   Time to become more like Elon Musk and start doing something with the many ideas I have brewing
   in this brain of mine.
